@startuml view

package View {
    class BaseView { 
        - statusView: bool
        + showMenu(): virtual void
        + showMenu(): virtual void
        + isShown(): bool
    }

    class ScanfOptionView {
        + showMenu(): void
    }

    class MediaFileView {
        + showMenu(): void
        + showMediaFilesPage(files: vector<MediaFile>, page: int): void
    }

    class PlaylistView {
        + showMenu()
        + showPlaylistList(playlists: vector<Playlist>)
    }

    class DetailedPlaylistView {
        + showMenu(): void
        + showPlaylistDetails(playlist: Playlist): void
        + showListofSongs(playlist: Playlist): void
    }

    class PlayingMediaView {
        + showMenu(): void
        + showSongInfo(file: MediaFile)
    }

    class MetadataView {
        + showMenu():
        + showFileMetadata(file: MediaFile): void
    }

    class ViewManager {
        - currentView: BaseView*
        + showCurrentMenu(): void
        + switchView(view: ViewBase): void
    }
    ViewManager o--> BaseView
    BaseView <|-- ScanfOptionView
    BaseView <|-- MediaFileView
    BaseView <|-- PlaylistView
    BaseView <|-- DetailedPlaylistView
    BaseView <|-- PlayingMediaView
    BaseView <|-- MetadataView
}

@enduml
