@startuml Controller
package Controller {
    class BaseController {
        + inputFromKeyboard(): virtual void
        + handleInput(): virtual void
    }

    class ScanfOptionController {
        + inputFromKeyboard(): void
        + handleInput(): void
        + scanDirectory(path: string): vector<MediaFile>
        + scanUSBDevice(): vector<MediaFile>
    }

    class PlaylistController {
        + inputFromKeyboard(): void
        + handleInput(): void
        + getAllPlaylists(): vector<Playlist>
        + createPlaylist(name: string): void
        + deletePlaylist(name: string): void
    }

    class MediaFileController {
        + inputFromKeyboard(): void
        + handleInput(): void
        + getAllMediaFiles(): vector<MediaFile>
        + getMediaFileDetails(name: string): MediaFile
    }

    class PlayingMediaController {
        + inputFromKeyboard(): void
        + handleInput(): void
        + playMediaFile(file: MediaFile)
        + play(): voida
        + pause(): void
        + stop(): void
        + skipToNext(): void
        + skipToPrevious(): void
        + adjustVolume(level: int): void
    }

    class DetailedPlaylistController {
        + inputFromKeyboard(): void
        + handleInput(): void
        + getPlaylistDetails(playlistName: string): Playlist
        + addSongToPlaylist(playlistName: string, song: MediaFile): void
        + removeSongFromPlaylist(playlistName: string, song: MediaFile): void
    }

    class MetadataController {
        + inputFromKeyboard(): void
        + handleInput(): void
        + getMediaFileMetadata(file: MediaFile): map<string, string>
        + updateMediaFileMetadata(file: MediaFile, metadata: map<string, string>): void
    }

    class ControllerManager {
        - controllers: vector<BaseController*>

    }

    ' Liên kết giữa các Controller
    BaseController <|-- ScanfOptionController
    BaseController <|-- PlaylistController
    BaseController <|-- MediaFileController
    BaseController <|-- PlayingMediaController
    BaseController <|-- DetailedPlaylistController
    BaseController <|-- MetadataController

    ControllerManager o--> BaseController
}
@enduml
