@startuml MVC
package Controller {

    ControllerManager --> FileController
    ControllerManager --> PlaylistController
    ControllerManager --> MediaFileController
    ControllerManager --> PlayingMediaController
    ControllerManager --> DetailedPlaylistController
    ControllerManager --> MetadataController
}

package Model {

    ModelManager --> MediaLibrary
    ModelManager --> PlaylistLibrary
    ModelManager --> PlayingMedia
    ModelManager --> Device
    MediaLibrary o--> MediaFile
    PlaylistLibrary o--> Playlist
    Playlist o--> MediaFile
    MediaFile o--> Metadata
}

package View {

    ViewScanfOption --|> ViewBase
    ViewMediaFile --|> ViewBase
    ViewPlaylist --|> ViewBase
    ViewDetailedPlaylist --|> ViewBase
    ViewPlay --|> ViewBase
    ViewMetadata --|> ViewBase
    ViewBase <--o ViewManager
}

package Hardware {
    Device "1" --> "1" KL46ZInterface : interfaces with >
}

ViewManager -- ControllerManager
ControllerManager -- ModelManager

@enduml